name: pokedex_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.0
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+5
  dio: ^5.1.2
  get_it: ^7.6.0
  intl: ^0.18.1
  flutter_svg: ^1.0.3
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.6
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
